export const GET_ALL_TASK_TYPE = "GET_ALL_TASK_TYPE";
export const GET_ALL_TASK_TYPE_SAGA = "GET_ALL_TASK_TYPE_SAGA";
export const GET_ALL_PRIORITY = "GET_ALL_PRIORITY";
export const GET_ALL_PRIORITY_SAGA = "GET_ALL_PRIORITY_SAGA";
export const GET_ALL_STATUS = "GET_ALL_STATUS";
export const GET_ALL_STATUS_SAGA = "GET_ALL_STATUS_SAGA";

export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA";

export const GET_TASK_DETAIL_SAGA = "GET_TASK_DETAIL_SAGA";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
export const CHANGE_TASK_MODAL = "CHANGE_TASK_MODAL";
export const REMOVE_USER_ASSIGN = "REMOVE_USER_ASSIGN";
export const CHANGE_ASSIGNESS = "CHANGE_ASSIGNESS";

export const HANDLE_CHANGE_POST_API_SAGA = "HANDLE_CHANGE_POST_API_SAGA";

export const GET_ALL_COMMENT = "GET_ALL_COMMENT";
export const GET_ALL_COMMENT_SAGA = "GET_ALL_COMMENT_SAGA";

export const ADD_COMMENT_SAGA = "ADD_COMMENT_SAGA";
export const ADD_COMMENT = "ADD_COMMENT";


export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";
export const EDIT_COMMENT_SAGA = "EDIT_COMMENT_SAGA";