export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_DRAWER = "OPEN_DRAWER";
export const SET_SUBMIT_EDIT_PROJECT = "SET_SUBMIT_EDIT_PROJECT";
export const SET_SUBMIT_EDIT_USER = "SET_SUBMIT_EDIT_USER";

export const GET_USER_API = "GET_USER_API";
export const ADD_USER_PROJECT_API = "ADD_USER_PROJECT_API";
export const REMOVE_USER_PROJECT_API = "REMOVE_USER_PROJECT_API";

export const OPEN_FORM = "OPEN_FORM";

export const GET_USER_BY_PROJECT_ID_SAGA = "GET_USER_BY_PROJECT_ID_SAGA";
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";

export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";
